// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

/*
 * Funções de Retorno de etapas no 
 * formulário de Envio de Plano de Negócio
 */

function retornaPrimeiraParte() {
    $("#anterior2").click(function (Event) {
        $("#formularioParte02").fadeOut(100)
        $("#formularioParte01").fadeIn(3200)
    });
}
function retornaSegundaParte() {
    $("#anterior3").click(function (Event) {
        $("#formularioParte03").fadeOut(100)
        $("#formularioParte02").fadeIn(3200)
    });
}
function retornaTerceiraParte() {
    $("#anterior4").click(function (Event) {
        $("#formularioParte04").fadeOut(100)
        $("#formularioParte03").fadeIn(3200)
    });
}
function retornaQuartaParte() {
    $("#anterior5").click(function (Event) {
        $("#formularioParte05").fadeOut(100)
        $("#formularioParte04").fadeIn(3200)
    });
}
function retornaQuintaParte() {
    $("#anterior6").click(function (Event) {
        $("#formularioParte06").fadeOut(100)
        $("#formularioParte05").fadeIn(3200)
    });
}

/*
 * Fim das funções de retorno de etapas do formulário --------------------------
 */

/*
 * Início das funções de exibição das próximas
 * etapas do formulário de Envio do Plano de Negócio
 */

function exibeSegundaParte() {
    $("#proximo2").click(function (Event) {
        $("#formularioParte01").fadeOut(100)
        $("#formularioParte02").fadeIn(3200)
    });
}
function exibeTerceiraParte() {
    $("#proximo3").click(function (Event) {
        $("#formularioParte02").fadeOut(100)
        $("#formularioParte03").fadeIn(3200)
    });
}
function exibeQuartaParte() {
    $("#proximo4").click(function (Event) {
        $("#formularioParte03").fadeOut(100)
        $("#formularioParte04").fadeIn(3200)
    });
}
function exibeQuintaParte() {
    $("#proximo5").click(function (Event) {
        $("#formularioParte04").fadeOut(100)
        $("#formularioParte05").fadeIn(3200)
    });
}
function exibeSextaParte() {
    $("#proximo6").click(function (Event) {
        $("#formularioParte05").fadeOut(100)
        $("#formularioParte06").fadeIn(3200)
    });
}

/*
 * Fim das funções de exibição
 * das próximas etapas do fomulário
 * de envio do plano de negócio
 * -----------------------------------------------------------------
 */