package com.ideiah.gerenciadorpampatec.model;
// Generated 31/08/2015 13:49:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Negocio generated by hbm2java
 */
public class Negocio  implements java.io.Serializable {


     private int idNegocio;
     private String segmentoClientes;
     private String propostaValor;
     private String atividadesChaves;
     private Set projetos = new HashSet(0);

    public Negocio() {
    }

	
    public Negocio(int idNegocio, String segmentoClientes, String propostaValor, String atividadesChaves) {
        this.idNegocio = idNegocio;
        this.segmentoClientes = segmentoClientes;
        this.propostaValor = propostaValor;
        this.atividadesChaves = atividadesChaves;
    }
    public Negocio(int idNegocio, String segmentoClientes, String propostaValor, String atividadesChaves, Set projetos) {
       this.idNegocio = idNegocio;
       this.segmentoClientes = segmentoClientes;
       this.propostaValor = propostaValor;
       this.atividadesChaves = atividadesChaves;
       this.projetos = projetos;
    }
   
    public int getIdNegocio() {
        return this.idNegocio;
    }
    
    public void setIdNegocio(int idNegocio) {
        this.idNegocio = idNegocio;
    }
    public String getSegmentoClientes() {
        return this.segmentoClientes;
    }
    
    public void setSegmentoClientes(String segmentoClientes) {
        this.segmentoClientes = segmentoClientes;
    }
    public String getPropostaValor() {
        return this.propostaValor;
    }
    
    public void setPropostaValor(String propostaValor) {
        this.propostaValor = propostaValor;
    }
    public String getAtividadesChaves() {
        return this.atividadesChaves;
    }
    
    public void setAtividadesChaves(String atividadesChaves) {
        this.atividadesChaves = atividadesChaves;
    }
    public Set getProjetos() {
        return this.projetos;
    }
    
    public void setProjetos(Set projetos) {
        this.projetos = projetos;
    }




}


