package com.ideiah.gerenciadorpampatec.model;
// Generated 31/08/2015 13:49:28 by Hibernate Tools 4.3.1



/**
 * Custo generated by hbm2java
 */
public class Custo  implements java.io.Serializable {


     private int idcusto;
     private Planofinanceiro planofinanceiro;
     private String nome;
     private boolean tipo;
     private float valor;

    public Custo() {
    }

    public Custo(int idcusto, Planofinanceiro planofinanceiro, String nome, boolean tipo, float valor) {
       this.idcusto = idcusto;
       this.planofinanceiro = planofinanceiro;
       this.nome = nome;
       this.tipo = tipo;
       this.valor = valor;
    }
   
    public int getIdcusto() {
        return this.idcusto;
    }
    
    public void setIdcusto(int idcusto) {
        this.idcusto = idcusto;
    }
    public Planofinanceiro getPlanofinanceiro() {
        return this.planofinanceiro;
    }
    
    public void setPlanofinanceiro(Planofinanceiro planofinanceiro) {
        this.planofinanceiro = planofinanceiro;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }




}


