package com.ideiah.gerenciadorpampatec.model;
// Generated 31/08/2015 13:49:28 by Hibernate Tools 4.3.1

import com.ideiah.gerenciadorpampatec.dao.ProjetoDao;
import com.ideiah.gerenciadorpampatec.dao.EmpreendedorDao;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Empreendedor generated by hbm2java
 */
public class Empreendedor implements java.io.Serializable {

    private int idEmpreendedor;
    private int idEndereco;
    private String senha;
    private String nome;
    private String telefone;
    private String cpf;
    private String email;
    private String formacao;
    private String experiencia;
    private String competencia;
    private String participacaoAcionaria;
    private String bairro;
    private String rua;
    private Integer numero;
    private String complemento;
    private Set projetos = new HashSet(0);

    private static EmpreendedorDao empreendedorDao;
    private static ProjetoDao projetoDao;

    public Empreendedor() {
        empreendedorDao = new EmpreendedorDao();
        projetoDao = new ProjetoDao();
    }

    /**
     * @return the empreededorDao
     */
    public static EmpreendedorDao getEmpreededorDao() {
        return empreendedorDao;
    }

    /**
     * @param aEmpreededorDao the empreededorDao to set
     */
    public static void setEmpreededorDao(EmpreendedorDao aEmpreededorDao) {
        empreendedorDao = aEmpreededorDao;
    }

    /**
     * @return the projetoDao
     */
    public static ProjetoDao getProjetoDao() {
        return projetoDao;
    }

    /**
     * @param aProjetoDao the projetoDao to set
     */
    public static void setProjetoDao(ProjetoDao aProjetoDao) {
        projetoDao = aProjetoDao;
    }

    public Empreendedor(int idEmpreendedor, String nome, String cpf, String email, String formacao, String senha, String rua, String bairro, int numero, String complemento) {
        this.idEmpreendedor = idEmpreendedor;
        this.nome = nome;
        this.cpf = cpf;
        this.email = email;
        this.formacao = formacao;
        this.senha = senha;
        this.rua = rua;
        this.bairro = bairro;
        this.numero = numero;
        this.complemento = complemento;
        empreendedorDao = new EmpreendedorDao();
        projetoDao = new ProjetoDao();
    }

    public Empreendedor(int idEmpreendedor, String nome, String telefone, String cpf, String email, String formacao, String experiencia, String competencia, String participacaoAcionaria, Set projetos, String senha) {
        this.idEmpreendedor = idEmpreendedor;
        this.nome = nome;
        this.telefone = telefone;
        this.cpf = cpf;
        this.email = email;
        this.formacao = formacao;
        empreendedorDao = new EmpreendedorDao();
        projetoDao = new ProjetoDao();
    }

    public Empreendedor(int idEmpreendedor, String nome, String telefone, String cpf, String email, String formacao, String experiencia, String competencia, String participacaoAcionaria, Set projetos) {
        this.idEmpreendedor = idEmpreendedor;
        this.nome = nome;
        this.telefone = telefone;
        this.cpf = cpf;
        this.email = email;
        this.formacao = formacao;
        this.experiencia = experiencia;
        this.competencia = competencia;
        this.participacaoAcionaria = participacaoAcionaria;
        this.projetos = projetos;
        empreendedorDao = new EmpreendedorDao();
        projetoDao = new ProjetoDao();
    }

    public int getIdEmpreendedor() {
        return this.idEmpreendedor;
    }

    public void setIdEmpreendedor(int idEmpreendedor) {
        this.idEmpreendedor = idEmpreendedor;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFormacao() {
        return this.formacao;
    }

    public void setFormacao(String formacao) {
        this.formacao = formacao;
    }

    public String getExperiencia() {
        return this.experiencia;
    }

    public void setExperiencia(String experiencia) {
        this.experiencia = experiencia;
    }

    public String getCompetencia() {
        return this.competencia;
    }

    public void setCompetencia(String competencia) {
        this.competencia = competencia;
    }

    public String getParticipacaoAcionaria() {
        return this.participacaoAcionaria;
    }

    public void setParticipacaoAcionaria(String participacaoAcionaria) {
        this.participacaoAcionaria = participacaoAcionaria;
    }

    public Set getProjetos() {
        return this.projetos;
    }

    public void setProjetos(Set projetos) {
        this.projetos = projetos;
    }

    public static boolean salvarProjeto(Projeto projeto) {
        if (false) {

        } else {

        }
        return false;
    }

    /**
     * @return the senha
     */
    public String getSenha() {
        return senha;
    }

    /**
     * @param senha the senha to set
     */
    public void setSenha(String senha) {
        this.senha = senha;
    }

    /**
     * Busca os empreendedores no banco.
     *
     * @return lista de empreendedores cadastrados.
     */
    public static List<Empreendedor> retornarEmpreendedores() {
        empreendedorDao = new EmpreendedorDao();
        return empreendedorDao.buscar();
    }
    /*
     *
     */

    public void cadastrarEmpreendedor(Empreendedor empreendedorNovo) {
        System.out.println("Entrou na CADASTRAR EMPREENDEDOR na Empreendedor");
        boolean retorno = empreendedorDao.buscarDados(empreendedorNovo.getEmail(), empreendedorNovo.getNome());
        int idEndereco = 0;
        if (retorno == true) {
            empreendedorDao.salvar(empreendedorNovo);
        }

    }

    public Empreendedor buscarPorEmail(String user) {
        return empreendedorDao.buscarPorEmail(user);
    }

    public Empreendedor buscarPorCpf(String user) {
        return empreendedorDao.buscarPorCpf(user);
    }

    /**
     * @return the idEndereco
     */
    public int getIdEndereco() {
        return idEndereco;
    }

    /**
     * @param idEndereco the idEndereco to set
     */
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }
    /*
    *
     */

    public void realizarCadastro() {
        getEmpreededorDao().salvar(this);
    }

    public static ArrayList<Empreendedor> buscaEmpreendedores() {
        return getEmpreededorDao().buscar();
    }

    /**
     * @return the numero
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * @param numero the numero to set
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * @return the complemento
     */
    public String getComplemento() {
        return complemento;
    }

    /**
     * @param complemento the complemento to set
     */
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    /**
     * @return the bairro
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * @param bairro the bairro to set
     */
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    /**
     * @return the rua
     */
    public String getRua() {
        return rua;
    }

    /**
     * @param rua the rua to set
     */
    public void setRua(String rua) {
        this.rua = rua;
    }

}
