package com.ideiah.gerenciadorpampatec.model;
// Generated 31/08/2015 13:49:28 by Hibernate Tools 4.3.1

import com.ideiah.gerenciadorpampatec.dao.ProjetoDao;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projeto generated by hbm2java
 */
public class Projeto implements java.io.Serializable {

    public static final int EM_EDICAO = 0;
    public static final int EM_PRE_AVALIACAO = 1;
    public static final int APROVADO = 2;
    public static final int REPROVADO = 3;
    public static final int EM_CORRECAO = 4;

    private Integer idProjeto;
    private Analiseemprego analiseemprego;
    private Negocio negocio;
    private Planofinanceiro planofinanceiro;
    private Produtoouservico produtoouservico;
    private String nome;
    private Date dataEnvio;
    private Integer status;
    private String potencialEmprego;
    private Set empreendedores = new HashSet(0);
    private String participacaoacionaria;
    private String edital;
    private Date dataCriacao;
    
    private GerenteRelacionamento gerenteRelacionamento;
    
    public Projeto() {
    }

    public Projeto(Integer idProjeto, Analiseemprego analiseemprego, Negocio negocio, Planofinanceiro planofinanceiro, Produtoouservico produtoouservico, String participacaoacionaria) {
        this.idProjeto = idProjeto;
        this.analiseemprego = analiseemprego;
        this.negocio = negocio;
        this.planofinanceiro = planofinanceiro;
        this.produtoouservico = produtoouservico;
        this.participacaoacionaria = participacaoacionaria;
    }

    public Projeto(Integer idProjeto, Analiseemprego analiseemprego, Negocio negocio, Planofinanceiro planofinanceiro, Produtoouservico produtoouservico, String nome, Date dataEnvio, Integer status, String potencialEmprego, Set empreendedors, String participacaoacionaria, String edital,
            Date dataCriacao, GerenteRelacionamento gerenteDeRelacionamento) {
        this.idProjeto = idProjeto;
        this.analiseemprego = analiseemprego;
        this.negocio = negocio;
        this.planofinanceiro = planofinanceiro;
        this.produtoouservico = produtoouservico;
        this.nome = nome;
        this.dataEnvio = dataEnvio;
        this.status = status;
        this.potencialEmprego = potencialEmprego;
        this.empreendedores = empreendedors;
        this.participacaoacionaria = participacaoacionaria;
        this.edital = edital;
        this.dataCriacao = dataCriacao;
        this.gerenteRelacionamento = gerenteDeRelacionamento;
    }

    public boolean SalvarProjeto(Projeto projeto) {
        ProjetoDao projetoDao = new ProjetoDao();
        try {
            projetoDao.update(projeto);
            return true;
        } catch (Exception e) {
        }
        return false;
    }

    public Integer getIdProjeto() {
        return this.idProjeto;
    }

    public void setIdProjeto(Integer idProjeto) {
        this.idProjeto = idProjeto;
    }

    public Analiseemprego getAnaliseemprego() {
        return this.analiseemprego;
    }

    public void setAnaliseemprego(Analiseemprego analiseemprego) {
        this.analiseemprego = analiseemprego;
    }

    public Negocio getNegocio() {
        return this.negocio;
    }

    public void setNegocio(Negocio negocio) {
        this.negocio = negocio;
    }

    public Planofinanceiro getPlanofinanceiro() {
        return this.planofinanceiro;
    }

    public void setPlanofinanceiro(Planofinanceiro planofinanceiro) {
        this.planofinanceiro = planofinanceiro;
    }

    public Produtoouservico getProdutoouservico() {
        return this.produtoouservico;
    }

    public void setProdutoouservico(Produtoouservico produtoouservico) {
        this.produtoouservico = produtoouservico;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Date getDataEnvio() {
        return this.dataEnvio;
    }

    public void setDataEnvio(Date dataEnvio) {
        this.dataEnvio = dataEnvio;
    }

    public Integer getStatus() {
        return this.status;
    }

    public String getStatusString(int status) {
        String statusDescricao = "";

        switch (status) {
            case EM_EDICAO:
                statusDescricao = "Em edição";
                break;
            case EM_PRE_AVALIACAO:
                statusDescricao = "Em Pré-Avaliação";
                break;
            case APROVADO:
                statusDescricao = "Aprovado";
                break;
            case REPROVADO:
                statusDescricao = "Reprovado";
                break;
            case EM_CORRECAO:
                statusDescricao = "Em correção";
                break;
        }

        return statusDescricao;

    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getPotencialEmprego() {
        return this.potencialEmprego;
    }

    public void setPotencialEmprego(String potencialEmprego) {
        this.potencialEmprego = potencialEmprego;
    }

    public Set getEmpreendedores() {
        return this.empreendedores;
    }

    public void setEmpreendedores(Set empreendedors) {
        this.empreendedores = empreendedors;
    }

    /**
     * @return the participacaoacionaria
     */
    public String getParticipacaoacionaria() {
        return participacaoacionaria;
    }

    /**
     * @param participacaoacionaria the participacaoacionaria to set
     */
    public void setParticipacaoacionaria(String participacaoacionaria) {
        this.participacaoacionaria = participacaoacionaria;
    }

    /**
     * @return the edital
     */
    public String getEdital() {
        return edital;
    }

    /**
     * @param edital the edital to set
     */
    public void setEdital(String edital) {
        this.edital = edital;
    }

    /**
     * @return the dataCriacao
     */
    public Date getDataCriacao() {
        return dataCriacao;
    }

    /**
     * @param dataCriacao the dataCriacao to set
     */
    public void setDataCriacao(Date dataCriacao) {
        this.dataCriacao = dataCriacao;
    }

    /**
     * @return the gerenteRelacionamento
     */
    public GerenteRelacionamento getGerenteRelacionamento() {
        return gerenteRelacionamento;
    }

    /**
     * @param gerenteRelacionamento the gerenteRelacionamento to set
     */
    public void setGerenteRelacionamento(GerenteRelacionamento gerenteRelacionamento) {
        this.gerenteRelacionamento = gerenteRelacionamento;
    }

}
